### ISSUE TITLE
Mod doesn't seem to work

### ISSUE THREAD

**Issue by JoelCrafter43** [GrahamKracker/BloonsClicker#3]
I think the game updating broke the mod as I don't see any way of actually using this mod when I get into a game with it installed

**Comment by CoolZManDude** [comment]
I have the exact same problem. I don't see the button to buy or use the cursor. I would like it if the description for the mod was more specific on how to use it

**Comment by BTD6Arg** [comment]
I also have the same problem i don't have the blue button to upgrade my cursor i would like a better description of how to use the mod.

**Comment by GoldenVibe** [comment]
I have the same problem when in game i dont see the upgrade tab plz fix i want to play it so bad

**Comment by Hause2001** [comment]
i am also having the same issue please help

**Comment by GrahamKracker** [comment]
fixed now that ryans video has been uploaded, download version 1.1.0
